--liquibase formatted sql

--changeset warlocktony:1
CREATE TABLE notification_task (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
chat_id BIGINT NOT NULL,
message VARCHAR(255) NOT NULL,
notification_date_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
CONSTRAINT "pk" PRIMARY KEY (id));
